global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app'
    static_configs:
      - targets: ['app1:8501', 'app2:8501']

  - job_name: 'mysql'
    static_configs:
      - targets: ['db:3306']

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']

  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']
